Repository sofa-framework/SofaPython3, pull requests merged in 2020-06, with the labels that each got.

#7 FIX: Downcast of Data
  Plugin/src/SofaPython3/PythonFactory.cpp
Labels: pr: fast-merge, status: to review

#8 ADD test for Data DownCast
  bindings/Sofa/tests/Core/BaseData.py
Labels: pr: fast-merge

#10 ImportPlugin now takes a pointer to the globals
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  Plugin/src/SofaPython3/PythonEnvironment.h
  Plugin/src/SofaPython3/PythonTest.cpp
  Plugin/src/SofaPython3/SceneLoaderPY3.cpp
Labels: pr: clean-fix, pr: fast-merge, status: to review

#14 ADD: sized-deallocation on test targets
  CMake/SofaPython3Tools.cmake
  Plugin/CMakeLists.txt
Labels: status: ready

#12 Install tests and remove empty input module
  CMake/SofaPython3Tools.cmake
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  bindings/Sofa/tests/CMakeLists.txt
  bindings/Sofa/tests/Core/PythonRestShapeForceField.py
  bindings/Sofa/tests/PythonModule_Sofa_test.cpp
  bindings/SofaExporter/tests/CMakeLists.txt
  bindings/SofaExporter/tests/PythonModule_SofaExporter_test.cpp
  bindings/SofaRuntime/CMakeLists.txt
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Input/Submodule_Input.cpp
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Input/Submodule_Input.h
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Input/Submodule_Input_doc.h
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
  bindings/SofaRuntime/tests/CMakeLists.txt
  bindings/SofaRuntime/tests/PythonModule_SofaRuntime_test.cpp
  bindings/SofaRuntime/tests/tests/Base.py
  bindings/SofaTypes/tests/CMakeLists.txt
  bindings/SofaTypes/tests/PythonModule_SofaTypes_test.cpp
Labels: status: to review

#13 [test] Add a github workflow for building and testing on ubuntu
  .github/workflows/ubuntu.yml
Labels: status: to review

#1 [SofaPython3] The coder returning "values" out of Basedata is broken
  Plugin/src/SofaPython3/PythonFactory.cpp
Labels: status: to review

#9 [cmake] Add XCode framework to RPath on MacOS
  CMake/SofaPython3Tools.cmake
  CMakeLists.txt
Labels: status: ready

#21 Fix ubuntu CI
  .github/workflows/ubuntu.yml
  bindings/Sofa/tests/Core/BaseData.py
Labels: pr: fast-merge, status: to review

#22 Add logging function to binding
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base_doc.h
  bindings/Sofa/tests/Core/Base.py
Labels: status: ready

#19 [cmake] Add installation RPATH of SP3 target dependencies.
  CMake/SofaPython3Tools.cmake
  bindings/Sofa/tests/CMakeLists.txt
  bindings/SofaRuntime/tests/CMakeLists.txt
  bindings/SofaTypes/tests/CMakeLists.txt
Labels: status: ready

#23 [SofaPython3] Restore the plugins automatic loading of python libraries.
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  Plugin/src/SofaPython3/PythonEnvironment.h
Labels: status: to review

#24 Add support for per component logging
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
Labels: status: ready
