Repository sofa-framework/SofaPython3, pull requests merged in 2020-11, with the labels that each got.

#63 [Bindings] Fix Vec/Mat template types
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.cpp
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.h
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.h
Labels: pr: clean-fix, pr: fast-merge, status: ready

#61 Fix vs2017 build
  CMakeLists.txt
  bindings/Sofa/tests/CMakeLists.txt
  bindings/SofaExporter/tests/CMakeLists.txt
  bindings/SofaGui/CMakeLists.txt
  bindings/SofaRuntime/tests/CMakeLists.txt
  bindings/SofaTypes/tests/CMakeLists.txt
Labels: pr: clean-fix, status: ready

#58 Cleaner test output
  Plugin/CMakeLists.txt
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  Plugin/src/SofaPython3/PythonTest.cpp
  Plugin/src/SofaPython3/PythonTest.h
  Plugin/src/SofaPython3/PythonTestExtractor.cpp
  Plugin/src/SofaPython3/PythonTestExtractor.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.cpp
  bindings/Sofa/tests/Core/Base.py
  bindings/Sofa/tests/Core/BaseData.py
  bindings/Sofa/tests/Core/BaseLink.py
  bindings/Sofa/tests/Core/BaseObject.py
  bindings/Sofa/tests/Core/Controller.py
  bindings/Sofa/tests/Core/ForceField.py
  bindings/Sofa/tests/PythonModule_Sofa_test.cpp
  bindings/Sofa/tests/Simulation/Node.py
  bindings/SofaRuntime/tests/PythonModule_SofaRuntime_test.cpp
  bindings/SofaTypes/tests/PythonModule_SofaTypes_test.cpp
Labels: status: to review

#67 SofaExporter bindings were still using the old PythonTestList class
  bindings/SofaExporter/tests/PythonModule_SofaExporter_test.cpp
Labels: pr: fast-merge, status: to review
