Repository sofa-framework/SofaPython3, pull requests merged in 2020-12, with the labels that each got.

#65 Fix tests
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  Plugin/src/SofaPython3/PythonTest.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Components/Submodule_Components.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseData.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Helper/Submodule_Helper.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Types/Submodule_Types.cpp
  bindings/Sofa/tests/Components/Components.py
  bindings/Sofa/tests/Core/BaseData.py
  bindings/Sofa/tests/Core/BaseObject.py
  bindings/Sofa/tests/Core/ForceField.py
  bindings/Sofa/tests/Core/MyRestShapeForceField.py
  bindings/Sofa/tests/Simulation/Node.py
  bindings/Sofa/tests/bench_datacontainer.py
  bindings/Sofa/tests/bench_node.py
  bindings/Sofa/tests/benchmark.py
  bindings/Sofa/tests/dataaccess.py
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
  bindings/SofaRuntime/tests/tests/Base.py
  examples/ControllerScene.py
Labels: status: ready

#55 Added bindings for camera methods
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera.cpp
Labels: status: to review

#71 [FIX/Packaging] Fix MSVC compilation and install in user directory (Windows)
  CMakeLists.txt
Labels: bug, status: ready

#69 Using pygalmesh to create volumetric meshes from surface meshes in SofaPython3
  splib/meshing/data/meshes/gallbladder.stl
  splib/meshing/pygalmesh_sofa.py
Labels: enhancement, status: ready

#75 Fix all tests on Windows
  CMake/SofaPython3Tools.cmake
  CMakeLists.txt
  bindings/CMakeLists.txt
  bindings/Modules/CMakeLists.txt
  bindings/Sofa/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
  bindings/Sofa/tests/CMakeLists.txt
  bindings/Sofa/tests/Core/ForceField.py
  bindings/Sofa/tests/Helper/FileRepository.py
  bindings/Sofa/tests/Simulation/Simulation.py
  bindings/SofaExporter/src/SofaExporter/Binding_STLExporter.cpp
  bindings/SofaExporter/src/SofaExporter/Binding_STLExporter.h
  bindings/SofaRuntime/tests/CMakeLists.txt
  bindings/SofaTypes/tests/CMakeLists.txt
Labels: status: to review

#79 [bindings] Fix missing plugins for forcefield tests
  bindings/Sofa/tests/Core/ForceField.py
  bindings/Sofa/tests/Core/PythonRestShapeForceField.py
Labels: pr: fast-merge, status: to review
