Repository sofa-framework/SofaPython3, pull requests merged in 2020-10, with the labels that each got.

#53 [FIX] broken plugin since Sofa PR #1491 & #1504
  Plugin/src/SofaPython3/DataHelper.h
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.cpp
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Mat.h
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.h
Labels: pr: fast-merge, status: ready

#52 Fix compilation with MSVC
  Plugin/src/SofaPython3/DataHelper.h
  bindings/SofaExporter/tests/tests/STLExporter.py
Labels: bug, pr: fast-merge, status: to review

#62 [CMake] Use sofa_add_plugin to make SofaPython3 deactivable
  CMakeLists.txt
Labels: enhancement, status: to review
