Repository sofa-framework/SofaPython3, pull requests merged in 2020-09, with the labels that each got.

#43 Add include_guard() and set default library path to python3/site-package
  CMake/SofaPython3Tools.cmake
  CMakeLists.txt
  Plugin/PluginConfig.cmake.in
  SofaPython3Config.cmake.in
  bindings/BindingsConfig.cmake.in
Labels: status: ready

#46 Various Fix in Prefab.
  Plugin/src/SofaPython3/Prefab.cpp
  bindings/Sofa/package/__init__.py
Labels: status: ready

#48 FIX prefab contructions helper
  bindings/Sofa/package/__init__.py
  bindings/Sofa/package/prefab.py
Labels: status: to review

#49 [bindings/Sofa] FIX 'name' was not properly set in a Sofa.Prefab
  bindings/Sofa/package/prefab.py
Labels: pr: fast-merge

#50 link SofaPython3::Plugin to Bindings.Sofa.Simulation
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeLists.txt
Labels: pr: fast-merge
