Repository sofa-framework/SofaPython3, pull requests merged in 2020-07, with the labels that each got.

#26 Replace all SofaAllCommonComponents occurrences by SofaComponentAll.
  bindings/Sofa/package/__init__.py
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera_doc.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseLink_doc.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseObject_doc.h
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation_doc.h
  bindings/Sofa/tests/Core/ForceField.py
  bindings/Sofa/tests/bench_datacontainer.py
  bindings/Sofa/tests/bench_node.py
  bindings/Sofa/tests/benchmark.py
  bindings/Sofa/tests/dataaccess.py
  bindings/Sofa/tests/minitest.py
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
  docs/sphinx-stubs/SofaRuntime/__init__.py
  docs/sphinx/source/menu/SofaPlugin.rst
  examples/ControllerScene.py
  examples/ReadTheDocs_Example.py
  examples/pygame_renderingloop/pygame_test.py
Labels: pr: fast-merge, status: ready

#20 Add a MacOS CI workflow
  .github/workflows/macos.yml
Labels: status: ready

#25 [cmake] Catch non-existing target properties for the dependency lookout.
  CMake/SofaPython3Tools.cmake
Labels: status: ready

#28 Change the SP3_PYTHON_PACKAGES_DIRECTORY cmake variable type to STRING
  CMakeLists.txt
Labels: status: to review

#30 changing attribute bindings of ObjectModel::ClassEntry
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ObjectFactory.cpp
Labels: pr: fast-merge, status: ready

#29 [Binding.Sofa.Core] FIX Link bindings
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseLink.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseLink.h
Labels: status: to review

#34 [SofaPython3/binding/Sofa] Add a first test for simulation.
  bindings/Sofa/tests/CMakeLists.txt
  bindings/Sofa/tests/Simulation/Simulation.py
Labels: pr: fast-merge, status: ready

#35 [SofaPython3] Add a per-keyword setData function
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base_doc.h
Labels: pr: fast-merge, status: ready

#18 [Bindings.Sofa.Helper] Add MessageHandler context manager class
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Helper/Binding_MessageHandler.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Helper/Binding_MessageHandler.h
  bindings/Sofa/src/SofaPython3/Sofa/Helper/Binding_MessageHandler_doc.h
  bindings/Sofa/src/SofaPython3/Sofa/Helper/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Helper/Submodule_Helper.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeLists.txt
  bindings/Sofa/tests/Helper/Message.py
  bindings/Sofa/tests/Simulation/Node.py
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
Labels: pr: new feature, status: ready
