Repository sofa-framework/SofaPython3, pull requests merged in 2021-01, with the labels that each got.

#78 [SofaDeformable] Bind LinearSpring
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  bindings/BindingsConfig.cmake.in
  bindings/Modules/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaDeformable/Binding_LinearSpring.cpp
  bindings/Modules/src/SofaPython3/SofaDeformable/Binding_LinearSpring.h
  bindings/Modules/src/SofaPython3/SofaDeformable/Binding_LinearSpring_doc.h
  bindings/Modules/src/SofaPython3/SofaDeformable/Binding_SpringForceField.cpp
  bindings/Modules/src/SofaPython3/SofaDeformable/Binding_SpringForceField.h
  bindings/Modules/src/SofaPython3/SofaDeformable/Binding_SpringForceField_doc.h
  bindings/Modules/src/SofaPython3/SofaDeformable/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaDeformable/Module_SofaDeformable.cpp
  bindings/Modules/tests/CMakeLists.txt
  bindings/Modules/tests/SofaDeformable/LinearSpring.py
  bindings/Modules/tests/SofaDeformable/SpringForceField.py
  bindings/Modules/tests/main.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ContactListener.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ContactListener.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ContactListener_doc.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
Labels: enhancement, status: to review

#82 Clean-ups before release
  CMake/SofaPython3Tools.cmake
  CMakeLists.txt
  Plugin/CMakeLists.txt
  bindings/Sofa/SofaPython3_SofaConfig.cmake.in
  bindings/Sofa/tests/Core/PythonRestShapeForceField.py
  runFromPython.py
  runSimu.py
  sofaenv.py
Labels: status: ready

#83 Improve CMake for v20.12
  CMake/SofaPython3Tools.cmake
  CMakeLists.txt
  Plugin/CMakeLists.txt
  Plugin/src/SofaPython3/PythonTestExtractor.cpp
  bindings/CMakeLists.txt
  bindings/Modules/tests/CMakeLists.txt
  bindings/Sofa/tests/CMakeLists.txt
  bindings/SofaExporter/CMakeLists.txt
  bindings/SofaExporter/tests/CMakeLists.txt
  bindings/SofaExporter/tests/PythonModule_SofaExporter_test.cpp
  bindings/SofaExporter/tests/tests/STLExporter.py
  bindings/SofaRuntime/tests/CMakeLists.txt
  bindings/SofaRuntime/tests/PythonModule_SofaRuntime_test.cpp
  bindings/SofaRuntime/tests/SofaRuntime/Base.py
  bindings/SofaTypes/tests/CMakeLists.txt
Labels: status: ready

#84 [examples] Add an advanced timer scene demonstration
  examples/advanced_timer.py
Labels: enhancement

#90 [cmake] Fix compilation issue on MacOS
  .github/workflows/macos.yml
  CMake/SofaPython3Tools.cmake
Labels: bug, pr: fast-merge, status: to review

#91 Added a binding for getLookAtFromOrientation
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera.cpp
Labels: enhancement, status: ready

#94 [cmake] Export SP3 cmake tools for usage in external projects
  CMake/SofaPython3Tools.cmake
  CMakeLists.txt
  Plugin/PluginConfig.cmake.in
  SofaPython3Config.cmake.in
  bindings/Modules/src/SofaPython3/SofaBaseTopology/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaDeformable/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Components/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Helper/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Types/CMakeLists.txt
  bindings/SofaExporter/CMakeLists.txt
  bindings/SofaGui/CMakeLists.txt
  bindings/SofaRuntime/CMakeLists.txt
  bindings/SofaTypes/CMakeLists.txt
Labels: enhancement, status: to review

#95 Wider RPATH for python modules
  CMake/SofaPython3Tools.cmake
  CMakeLists.txt
  SofaPython3Config.cmake.in
Labels: pr: fast-merge, status: to review

#96 Simplify RPATH
  CMake/SofaPython3Tools.cmake
Labels: pr: clean-fix, status: to review

#100 [Examples] Fix scenes before the release
  examples/CMakeLists.txt
  examples/advanced_timer.py
  examples/basic-addGUI.py
  examples/emptyController.py
  examples/emptyDataEngine.py
  examples/emptyForceField.py
  examples/example-forcefield.py
  examples/example-forcefield2.py
  examples/liver.py
  examples/loadXMLfromPython.py
Labels: pr: clean-fix, pr: fast-merge, status: to review

#97 [Examples] Remove the pygame scene as it is broken without glew bindings
  examples/CMakeLists.txt
  examples/pygame_renderingloop/backend_pygame.py
  examples/pygame_renderingloop/pygame_test.py
Labels: pr: clean-fix, status: ready

#99 [CMake] FIX SofaPython3Tools inclusion
  CMakeLists.txt
  SofaPython3Config.cmake.in
Labels: pr: clean-fix, pr: fast-merge

#101 [cmake] Remove RPATH debug message
  CMake/SofaPython3Tools.cmake
Labels: pr: clean-fix, pr: fast-merge, status: to review

#103 [SofaBaseTopology] Fix binding entry point
  bindings/Modules/src/SofaPython3/SofaBaseTopology/Module_SofaBaseTopology.cpp
Labels: pr: clean-fix, pr: fast-merge, status: to review

#104 [cmake] Fix missing module path for external projects
  CMakeLists.txt
  SofaPython3Config.cmake.in
Labels: pr: clean-fix, pr: fast-merge, status: to review

#105 [Plugin] Change the initialization order of the Prefab
  Plugin/src/SofaPython3/Prefab.cpp
Labels: pr: clean-fix, status: ready

#98 [Plugin] Remove unused files
  Plugin/src/SofaPython3/DataFactory.cpp
  Plugin/src/SofaPython3/DataFactory.h
  Plugin/src/SofaPython3/EventFactory.cpp
  Plugin/src/SofaPython3/EventFactory.h
Labels: pr: clean-fix, status: ready
