Repository sofa-framework/SofaPython3, pull requests merged in 2021-11, with the labels that each got.

#198 [SofaPython3] Changes how addObject process its arguments when they are of type: numpy & data
  Plugin/src/SofaPython3/DataHelper.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseData.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base_doc.h
  bindings/Sofa/tests/Core/Base.py
  bindings/Sofa/tests/Core/BaseData.py
Labels: pr: status ready, pr: new feature, pr: breaking, pr: highlighted in next release

#213 [GitHub] Rework the CI workflow based on sofa-setup-action
  .github/workflows/ci.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  bindings/Modules/tests/main.cpp
Labels: enhancement, pr: status ready

#217 [CI] FIX release tag name (do not use branch name)
  .github/workflows/ci.yml
Labels: pr: status to review, pr: clean-fix, pr: fast-merge
