Repository sofa-framework/SofaPython3, pull requests merged in 2021-07, with the labels that each got.

#154 [SofaPython3] Add an hasObject method in Binding_Node to detect if a node has an object.
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node_doc.h
  bindings/Sofa/tests/Simulation/Node.py
Labels: pr: new feature, status: to review

#155 [CMake] FIX pybind11 finding python
  CMakeLists.txt
Labels: pr: clean-fix, pr: fast-merge, status: ready

#157 [GitHub] Improve workflow for Ubuntu and MacOS
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  CMakeLists.txt
Labels: enhancement, status: ready

#156 [CMake] FIX pybind11 finding python (2)
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  SofaPython3Config.cmake.in
Labels: pr: clean-fix, pr: fast-merge, status: wip
