Repository sofa-framework/SofaPython3, pull requests merged in 2021-09, with the labels that each got.

#181 Upgrade Ubuntu builder to v20.04 + Clean versions
  .github/workflows/ubuntu.yml
Labels: pr: clean-fix, pr: fast-merge

#172 [SofaPython3] Remove splib from python3 plugin.
  CMakeLists.txt
  splib/__init__.py
  splib/animation/__init__.py
  splib/animation/animate.py
  splib/animation/easing.py
  splib/caching/__init__.py
  splib/caching/cacher.py
  splib/meshing/__init__.py
  splib/meshing/cgal_sofa.py
  splib/meshing/data/meshes/gallbladder.stl
  splib/meshing/data/meshes/parametric_mesh_example.step
  splib/meshing/data/meshes/surface_mesh_example.stl
  splib/meshing/gmsh_sofa.py
  splib/meshing/pygalmesh_sofa.py
Labels: status: ready, pr: clean-fix

#171 [Binding/Sofa.Core] FIX Node iterators.
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_NodeIterator.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_NodeIterator.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node_doc.h
  bindings/Sofa/tests/Simulation/Node.py
Labels: status: ready, pr: clean-fix, pr: new feature

#174 [Binding] Improves of the setting of data field of type string.
  Plugin/src/SofaPython3/PythonFactory.cpp
  bindings/Sofa/tests/Core/BaseData.py
Labels: status: ready

#178 [Binding/Sofa.Core] Add the python call stack to deprecation message.
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  bindings/Sofa/package/__init__.py
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Labels: enhancement, status: ready

#179 [Binding/Sofa.Core] Implement a custom getClassName() for trampoline classes.
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.h
Labels: status: ready, pr: clean-fix

#176 [Binding/Sofa.Core] Replace a std::cout with an exception.
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
Labels: status: ready

#185 [BaseCamera] add setDefaultView bindings
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera.cpp
Labels: status: ready, pr: new feature, pr: fast-merge

#188 [Plugin] Add calling point for the msg_deprecated emitted by PythonFactory;
  Plugin/src/SofaPython3/PythonFactory.cpp
Labels: status: ready

#177 Remove usage of boost::filesystem
  Plugin/src/SofaPython3/PythonTest.h
  Plugin/src/SofaPython3/PythonTestExtractor.cpp
Labels: status: ready, pr: clean-fix

#190 [Win/MSVC] Fix search of modules
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  Plugin/src/SofaPython3/PythonEnvironment.h
Labels: status: to review, pr: clean-fix, pr: fast-merge

#192 [CMake] Always use "lib" for LIBRARY_OUTPUT_DIRECTORY
  CMake/SofaPython3Tools.cmake
  CMakeLists.txt
Labels: status: to review, pr: clean-fix

#196 [examples] Remove splib related examples.
  examples/BaseCamera.py
  examples/CMakeLists.txt
  examples/easingScene.py
  examples/easingSceneMatplotlib.py
  examples/realTimeClockScene.py
Labels: status: ready, pr: clean-fix, pr: fast-merge

#183 [github] ADD ci-build workflow
  .github/workflows/ci-build.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
Labels: enhancement, status: ready

#187 [Binding/Sofa] FIX python calling point
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  bindings/Sofa/package/__init__.py
Labels: status: ready

#189 [SofaPython3] Add in DataHelper dedicated to-string conversion from basedata
  Plugin/src/SofaPython3/DataHelper.cpp
Labels: status: ready

#194 [Plugin] Refactor PythonEnvironment init
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  Plugin/src/SofaPython3/PythonEnvironment.h
Labels: status: ready, pr: clean-fix, pr: breaking

#191 [SofaPython3/splib] Add a gentle deprecation message and info on how to find the SPLIB.
  CMakeLists.txt
  splib/__init__.py
Labels: status: ready

#193 [CMake] CLEAN test resources location (still in bin)
  bindings/Modules/tests/CMakeLists.txt
  bindings/Modules/tests/main.cpp
  bindings/Sofa/tests/CMakeLists.txt
  bindings/Sofa/tests/PythonModule_Sofa_test.cpp
  bindings/SofaRuntime/tests/CMakeLists.txt
  bindings/SofaRuntime/tests/PythonModule_SofaRuntime_test.cpp
  bindings/SofaTypes/tests/CMakeLists.txt
  bindings/SofaTypes/tests/PythonModule_SofaTypes_test.cpp
Labels: enhancement, status: ready, pr: clean-fix

#199 [Sofa.Core.Node]: Improve deprecation message when using getobject.
  Plugin/src/SofaPython3/PythonFactory.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Labels: status: ready

#170 [MSVC] Fix link error in debug configuration
  Plugin/src/SofaPython3/PythonEnvironment.h
Labels: status: to review, pr: clean-fix

#180 [SofaPython3] Improves exception handling
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  Plugin/src/SofaPython3/PythonEnvironment.h
  Plugin/src/SofaPython3/SceneLoaderPY3.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.cpp
Labels: enhancement, status: ready

#202 [Sofa.Core.Binding] Remove suprious exception handler in Binding_DataEngine
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_DataEngine.cpp
Labels: pr: status ready, pr: fast-merge

#201 [BaseCamera] binding for rotateWorldAroundPoint()
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseCamera.cpp
Labels: pr: status to review, pr: fast-merge

#200 [Sofa.Core.BaseData] Add to the binding a method BaseData::setParent from a link path
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseData.cpp
Labels: pr: status ready, pr: fast-merge
