Repository sofa-framework/SofaPython3, pull requests merged in 2021-02, with the labels that each got.

#108 [All] Follow sofa master branch
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  Plugin/CMakeLists.txt
  Plugin/PluginConfig.cmake.in
  Plugin/src/SofaPython3/PythonEnvironment.h
  Plugin/src/SofaPython3/SceneLoaderPY3.cpp
  bindings/BindingsConfig.cmake.in
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseObject.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_PythonScriptEvent.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_PythonScriptEvent.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
  bindings/SofaGui/CMakeLists.txt
  bindings/SofaGui/src/SofaPython3/SofaGui/Binding_GUIManager.cpp
  bindings/SofaGui/src/SofaPython3/SofaGui/Module_SofaGui.cpp
  bindings/SofaRuntime/CMakeLists.txt
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Timer/Submodule_Timer.cpp
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.h
Labels: pr: clean-fix, status: ready

#109 [SofaGL] Start a Sofa.SofaGL Module
  bindings/Modules/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaGL/Binding_DrawToolGL.cpp
  bindings/Modules/src/SofaPython3/SofaGL/Binding_DrawToolGL.h
  bindings/Modules/src/SofaPython3/SofaGL/Binding_DrawToolGL_doc.h
  bindings/Modules/src/SofaPython3/SofaGL/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaGL/Module_SofaGL.cpp
  examples/additional-examples/pygame_example.py
  examples/additional-examples/pyqt_example.py
Labels: enhancement, status: ready

#111 [examples] fixed gl initialization in visualization examples
  examples/additional-examples/pygame_example.py
  examples/additional-examples/pyqt_example.py
Labels: status: ready

#112 [Bindings/SofaTypes] static_assert on cross()
  bindings/SofaTypes/src/SofaPython3/SofaTypes/Binding_Vec.cpp
Labels: pr: clean-fix, pr: fast-merge, status: ready

#114 [bindings] Started Topology and BaseMeshTopology bindings
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseContext.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseMeshTopology.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_BaseMeshTopology.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Topology.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Topology.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
Labels: status: ready

#115 [Plugin] Remove useless ArgumentParser include
  Plugin/src/SofaPython3/SceneLoaderPY3.cpp
Labels: pr: clean-fix, pr: fast-merge, status: ready

#116 [cmake] CMake config was exporting the wrong python version
  SofaPython3Config.cmake.in
Labels: pr: backport me, pr: clean-fix, pr: fast-merge, status: ready
