Repository sofa-framework/SofaPython3, pull requests merged in 2022-10, with the labels that each got.

#307 [CMake] Speed-up Configuration
  CMakeLists.txt
  Plugin/CMakeLists.txt
  bindings/Modules/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaBaseTopology/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaConstraintSolver/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaDeformable/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaGL/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaLinearSolver/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Components/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Core/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Helper/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/CMakeLists.txt
  bindings/Sofa/src/SofaPython3/Sofa/Types/CMakeLists.txt
  bindings/SofaExporter/CMakeLists.txt
  bindings/SofaGui/CMakeLists.txt
  bindings/SofaRuntime/CMakeLists.txt
  bindings/SofaTypes/CMakeLists.txt
Labels: pr: status ready, pr: clean-fix

#308 Lower number of steps in scene tests
  examples/.scene-tests
Labels: pr: status ready, pr: fast-merge

#312 [Example/Tests] Add events in the constraint solver pipeline
  bindings/Sofa/tests/CMakeLists.txt
  bindings/Sofa/tests/Core/Events.py
  examples/access_compliance_matrix.py
Labels: pr: status ready
