Repository sofa-framework/SofaPython3, pull requests merged in 2022-07, with the labels that each got.

#286 [Sofa.Gui] Fix macro to enable qt.conf
  bindings/SofaGui/src/SofaPython3/SofaGui/Module_SofaGui.cpp
Labels: pr: status ready, pr: clean-fix, pr: fast-merge

#288 [SofaPython3/Plugin] Add GetCustomClassName to Prefab
  Plugin/src/SofaPython3/Prefab.h
Labels: pr: status to review, pr: fast-merge

#284 [SofaPython3] Separates the pre-loaded python modules out of the python (Fix issue #283)
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  Plugin/src/SofaPython3/PythonEnvironment.h
Labels: issue: bug, pr: status ready, pr: fast-merge

#289 Binding to access to the compliance matrix in constraint space
  bindings/Modules/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaConstraintSolver/Binding_ConstraintSolver.cpp
  bindings/Modules/src/SofaPython3/SofaConstraintSolver/Binding_ConstraintSolver.h
  bindings/Modules/src/SofaPython3/SofaConstraintSolver/Binding_ConstraintSolver_doc.h
  bindings/Modules/src/SofaPython3/SofaConstraintSolver/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaConstraintSolver/Module_SofaConstraintSolver.cpp
  bindings/Modules/tests/CMakeLists.txt
  bindings/Modules/tests/SofaConstraintSolver/matrix_access.py
  bindings/Modules/tests/SofaLinearSolver/matrix_access.py
  bindings/Modules/tests/main.cpp
  examples/access_compliance_matrix.py
Labels: enhancement, pr: status ready
