Repository sofa-framework/SofaPython3, pull requests merged in 2022-03, with the labels that each got.

#238 [CI] ADD is_nightly parameter
  .github/workflows/ci.yml
Labels: enhancement, pr: status to review

#240 [CI] Force SOFA scope to 'minimal'
  .github/workflows/ci.yml
Labels: pr: status to review, pr: clean-fix, pr: fast-merge

#241 Restore xml and python different naming conventions
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Labels: pr: clean-fix

#239 [Binding/Sofa.Core] Update MechanicalObject Target in test
  bindings/Sofa/tests/Core/BaseObject.py
Labels: pr: status to review, pr: clean-fix
