Repository sofa-framework/SofaPython3, pull requests merged in 2022-12, with the labels that each got.

#318 [DataHelper] Change default access of vector data buffer
  Plugin/src/SofaPython3/DataHelper.cpp
Labels: pr: status ready

#316 Add a counter to memcach so that we can detect data change
  Plugin/src/SofaPython3/DataHelper.cpp
  Plugin/src/SofaPython3/DataHelper.h
  bindings/Sofa/tests/Core/BaseData.py
Labels: enhancement, pr: status ready

#322 Add addObject spelling support (again)
  Plugin/CMakeLists.txt
  Plugin/src/SofaPython3/SpellingSuggestionHelper.h
  Plugin/src/SofaPython3/config.h.in
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Base.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Labels: pr: status ready, pr: fast-merge

#323 Update plugins in unit tests
  bindings/Modules/tests/SofaDeformable/SpringForceField.py
Labels: pr: status to review, pr: clean-fix, pr: fast-merge

#324 Remove deprecated sofa::type::Vector3 in bindings.
  bindings/Modules/src/SofaPython3/SofaBaseTopology/Binding_SparseGridTopology.cpp
  bindings/Modules/src/SofaPython3/SofaLinearSolver/Binding_LinearSolver.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ContactListener.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ForceField.cpp
  bindings/SofaExporter/src/SofaExporter/Binding_STLExporter.cpp
  bindings/SofaExporter/src/SofaExporter/Binding_VisualModelOBJExporter.cpp
Labels: pr: status ready

#326 Remove v22.06 for the CI
  .github/workflows/ci.yml
Labels: pr: status ready, pr: fast-merge

#325 Fix: mass binding is defined to have multiple inheritance
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Mass.cpp
Labels: pr: status ready, pr: clean-fix
