Repository sofa-framework/SofaPython3, pull requests merged in 2022-06, with the labels that each got.

#259 Add bindings for all data types supported by SpringForceField + example
  bindings/Modules/src/SofaPython3/SofaDeformable/Binding_SpringForceField.cpp
  examples/springForceField.py
Labels: enhancement, pr: status ready

#255 [Sofa.Core] Print the event when printLog is activated.
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller.cpp
Labels: enhancement, pr: status ready

#263 [SofaGui] Update GUI related modules
  bindings/SofaGui/Bindings.SofaGuiConfig.cmake.in
  bindings/SofaGui/CMakeLists.txt
  bindings/SofaGui/src/SofaPython3/SofaGui/Binding_BaseGui.cpp
  bindings/SofaGui/src/SofaPython3/SofaGui/Binding_GUIManager.cpp
Labels: pr: status ready, pr: clean-fix

#269 Organize targets into Bindings folder
  bindings/CMakeLists.txt
  bindings/Sofa/CMakeLists.txt
Labels: pr: status to review, pr: fast-merge

#272 Revert "Organize targets into Bindings folder"
  bindings/CMakeLists.txt
  bindings/Sofa/CMakeLists.txt
Labels: pr: clean-fix

#266 [Plugin] Fix compilation for msvc and python 3.10
  Plugin/src/SofaPython3/DataHelper.h
Labels: pr: status ready, pr: clean-fix, pr: fast-merge

#273 [CMake] FIX missing find_package in Config
  bindings/Sofa/Bindings.SofaConfig.cmake.in
Labels: pr: status to review, pr: fast-merge

#261 Catch exception if Sofa cannot be imported
  Plugin/src/SofaPython3/PythonEnvironment.cpp
Labels: pr: status ready

#274 [CI] Consistent python version
  .github/workflows/ci.yml
Labels: pr: status ready, pr: fast-merge

#276 [SofaPyhon3/Plugin] Fix regression introduced in PR #243
  Plugin/src/SofaPython3/DataHelper.cpp
Labels: pr: status ready, pr: fast-merge

#277 [Sofa.Prefab] Replace Sofa.Prefab "properties"
  bindings/Sofa/package/prefab.py
Labels: pr: status ready, pr: fast-merge

#279 [FIX] Remove SofaLinearSolver in BindingsConfig.cmake.in
  bindings/BindingsConfig.cmake.in
Labels: issue: bug, pr: status ready, pr: fast-merge

#271 [FIX] The callpoint api is broken since SofaPython3.
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  Plugin/src/SofaPython3/SceneLoaderPY3.cpp
  bindings/Sofa/package/prefab.py
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Labels: pr: status ready, pr: clean-fix
