Repository sofa-framework/SofaPython3, pull requests merged in 2022-04, with the labels that each got.

#243 [SofaPython3/Binding] Do not use the binding cache mecanisme when the data is dirty (Fix sofa issue #2761)
  Plugin/src/SofaPython3/DataHelper.cpp
Labels: pr: status ready, pr: fast-merge

#248 [SofaaPython/Binding] Add py::keep_alive in Binding_Node.cpp (FIX issue #245)
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Labels: pr: status ready, pr: clean-fix, pr: fast-merge

#249 FIX PYBIND11_SOFA_VERSION
  Plugin/CMakeLists.txt
  Plugin/src/SofaPython3/DataCache.h
  Plugin/src/SofaPython3/PythonEnvironment.h
  Plugin/src/SofaPython3/PythonFactory.h
  Plugin/src/SofaPython3/SceneLoaderPY3.h
  Plugin/src/SofaPython3/config.h.in
  Plugin/src/SofaPython3/initModule.cpp
Labels: pr: status to review, pr: clean-fix

#182 [SofaPython3/Plugin] Restore the automatic reload of modules
  Plugin/src/SofaPython3/PythonEnvironment.cpp
Labels: pr: status to review, pr: clean-fix

#252 [SofaPython3] Fix regression introduced in #PR182
  Plugin/src/SofaPython3/PythonEnvironment.cpp
Labels: pr: status to review, pr: clean-fix, pr: fast-merge
