Repository sofa-framework/SofaPython3, pull requests merged in 2023-01, with the labels that each got.

#327 Add unit test for Mass multiple inheritance
  bindings/Sofa/tests/Core/Mass.py
Labels: enhancement, pr: status ready

#328 [CI] Fix mac ci with homebrew workaround
  .github/workflows/ci.yml
Labels: pr: status ready, pr: clean-fix, pr: fast-merge

#331 [Bindings.SofaGui] Fix compilation without compat layer
  bindings/SofaGui/Bindings.SofaGuiConfig.cmake.in
  bindings/SofaGui/CMakeLists.txt
  bindings/SofaGui/src/SofaPython3/SofaGui/Module_SofaGui.cpp
Labels: pr: status ready, pr: clean-fix
