Repository sofa-framework/SofaPython3, pull requests merged in 2024-07, with the labels that each got.

#421 [Slicer-SOFA integration] Add compatibility with GCC
  Testing/src/SofaPython3Testing/PythonTest.h
Labels: enhancement, pr: status ready

#422 Introduce binding to dump the object factory in json format
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ObjectFactory.cpp
  bindings/Sofa/tests/Core/ObjectFactory.py
Labels: enhancement, pr: status ready

#430 Support for Debug DLLs
  bindings/Sofa/package/__init__.py
Labels: enhancement, pr: status to review

#423 Follow SOFA change for init/updatevisual
  Plugin/src/SofaPython3/Prefab.cpp
Labels: pr: status ready

#434 Add binding for GUI::centerWindow
  bindings/SofaGui/src/SofaPython3/SofaGui/Binding_GUIManager.cpp
Labels: pr: status to review, pr: new feature, pr: fast-merge

#426 Add new env.var to set a build configuration at runtime
  bindings/Sofa/package/__init__.py
Labels: pr: status ready, pr: new feature

#431 Add functions to load plugins automatically
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
Labels: pr: status ready
