Repository sofa-framework/SofaPython3, pull requests merged in 2024-03, with the labels that each got.

#396 Introduce bindings to linear system
  bindings/Modules/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaLinearSystem/Binding_LinearSystem.cpp
  bindings/Modules/src/SofaPython3/SofaLinearSystem/Binding_LinearSystem.h
  bindings/Modules/src/SofaPython3/SofaLinearSystem/Binding_LinearSystem_doc.h
  bindings/Modules/src/SofaPython3/SofaLinearSystem/CMakeLists.txt
  bindings/Modules/src/SofaPython3/SofaLinearSystem/Module_SofaLinearSystem.cpp
  examples/access_mass_matrix.py
Labels: enhancement, pr: status ready, pr: new feature

#398 Add headers to the library so they're visible in IDE
  CMake/SofaPython3Tools.cmake
Labels: pr: status ready, pr: fast-merge

#403 Fix out-of-tree compilation of dependencies
  SofaPython3Config.cmake.in
Labels: pr: status ready, pr: clean-fix

#402 Update ci.yml
  .github/workflows/ci.yml
Labels: pr: status ready, pr: clean-fix

#404 fix Versioning to allow patches
  CMakeLists.txt
  SofaPython3Config.cmake.in
Labels: pr: status ready, pr: backport todo

#375 [Environment] Fix test for plugins envvars
  Plugin/src/SofaPython3/PythonEnvironment.cpp
Labels: pr: status ready, pr: clean-fix, pr: fast-merge
