Repository sofa-framework/SofaPython3, pull requests merged in 2024-09, with the labels that each got.

#447 Use PyMem_RawFree when resetting PythonEnvironmentData
  Plugin/src/SofaPython3/PythonEnvironment.cpp
Labels: pr: status ready, pr: clean-fix, pr: fast-merge

#424 Add two testing features
  Testing/src/SofaPython3Testing/PythonTest.cpp
  Testing/src/SofaPython3Testing/PythonTestExtractor.cpp
  bindings/Sofa/package/__init__.py
  bindings/Sofa/tests/Core/Mass.py
  examples/import_python_scene.py
Labels: pr: status ready

#448 CI upload artifact version update
  .github/workflows/ci.yml
Labels: pr: status to review

#455 Fix missing name in ClassEntry Binding_ObjectFactory.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ObjectFactory.cpp
Labels: pr: status to review, pr: fast-merge

#458 Fix missing plugins
  bindings/Sofa/tests/Core/BaseData.py
  bindings/Sofa/tests/Core/BaseMeshTopology.py
  bindings/Sofa/tests/Core/BaseObject.py
  bindings/Sofa/tests/Core/Mass.py
Labels: pr: status ready, pr: clean-fix, pr: fast-merge
