Repository sofa-framework/SofaPython3, pull requests merged in 2024-08, with the labels that each got.

#436 [Bindings.Gui] Add binding on BaseGui::setConfigDirectoryPath
  bindings/SofaGui/src/SofaPython3/SofaGui/Binding_BaseGui.cpp
Labels: pr: status to review, pr: new feature

#438 Fix wrong doc string for dump_json
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ObjectFactory.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_ObjectFactory_doc.h
Labels: pr: status ready, pr: clean-fix, pr: fast-merge

#439 add binding to unload a plugin
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
Labels: pr: status to review

#441 Display attribute_error with msg_error
  Plugin/src/SofaPython3/SceneLoaderPY3.cpp
Labels: pr: status ready, pr: clean-fix, pr: fast-merge

#432 [Bindings] Remove static SofaInitializer, call unload into each respective module and clear cache
  .github/workflows/ci.yml
  Plugin/src/SofaPython3/DataHelper.cpp
  Plugin/src/SofaPython3/DataHelper.h
  Plugin/src/SofaPython3/PythonEnvironment.cpp
  Plugin/src/SofaPython3/PythonEnvironment.h
  bindings/Sofa/src/SofaPython3/Sofa/Core/Submodule_Core.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Helper/Submodule_Helper.cpp
  bindings/Sofa/src/SofaPython3/Sofa/Simulation/Submodule_Simulation.cpp
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
Labels: pr: status ready, pr: clean-fix
