Repository sofa-framework/SofaPython3, pull requests merged in 2025-07, with the labels that each got.

#515 Update notify dash
  .github/workflows/ci.yml
Labels: pr: fast-merge

#523 Fix legacy version in RAII mechanism for numpy compatibility
  bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Node.cpp
Labels: pr: status ready, pr: backport todo

#513 Register objects from auto-loaded plugins
  bindings/SofaRuntime/src/SofaPython3/SofaRuntime/Module_SofaRuntime.cpp
Labels: enhancement, pr: status ready
